# 1. Create an array in numpy

In [1]:
import numpy as np

In [2]:
np.array([1,3,5,7])

array([1, 3, 5, 7])

In [3]:
## 2 dimensional array
np.array([(1,2,3,4),(2,4,5,7)])

array([[1, 2, 3, 4],
       [2, 4, 5, 7]])

In [4]:
## create array from list
num=[1,3,5,7]
np.array(num)

array([1, 3, 5, 7])

In [5]:
print(np.array(num))

[1 3 5 7]


## 1.1 generating array

In [6]:
## generating an identity array
num=np.identity(4)
print(num)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
np.identity(4)*7

array([[7., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 7.]])

In [8]:
num*7

array([[7., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 7.]])

In [9]:
## generating array of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
## generating array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
## generating a array in a range or interval
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
np.arange(0,10,2)
## we can control the step size

array([0, 2, 4, 6, 8])

In [15]:
## we can use linspace to generate an evenly spaced numbers
np.linspace(1,50,7)

array([ 1.        ,  9.16666667, 17.33333333, 25.5       , 33.66666667,
       41.83333333, 50.        ])

## generating array with random values

In [16]:
np.random.rand(4)

array([0.19589775, 0.37628425, 0.43135738, 0.5961601 ])

In [17]:
np.random.rand(4,5)

array([[0.68068057, 0.24583611, 0.58650331, 0.35668891, 0.15770472],
       [0.8677243 , 0.01078195, 0.39043689, 0.949732  , 0.95227182],
       [0.71754739, 0.15713737, 0.05170693, 0.52964679, 0.12052828],
       [0.95401595, 0.11453746, 0.83793266, 0.06751134, 0.65610699]])

In [18]:
## generate 1 random integer in a given range
np.random.randint(5,50)

31

In [19]:
# generate 5 random integers in given range
np.random.randint(0,50,5)

array([ 6,  4, 30, 15,  4])

In [20]:
# for take same output from random values at all run times we use seed
np.random.seed(13)
np.random.randint(5,50)

23

#  2. Data Selection: indexing and slicing 

In [21]:
## indexing: selecting individual elements from the array
## slicing:selecting group of elements from array

In [22]:
num1=np.array([1,2,3,4,5])

In [23]:
# indexing
num1[1]

2

In [24]:
num1[-2]

4

In [25]:
# slicing
num1[2:5]

array([3, 4, 5])

In [26]:
num2=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [27]:
num2[1][2]
# remmber index start from 0

6

In [28]:
# selecting whole row
num2[2]

array([7, 8, 9])

In [29]:
# selecting 2 rows from 0 to 2
num2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# selecting last 2 rows and first 2 columns
num2[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [31]:
# selecting last 2 columns
num2[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

## 2.2 conditional selection  

In [32]:
num3=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [33]:
num3[num3<6]

array([1, 2, 3, 4, 5])

In [34]:
num3[num3>6]

array([7, 8, 9])

In [35]:
num3[num3 %2 ==0]

array([2, 4, 6, 8])

In [36]:
num3[(num3%2 !=0) & (num3>5)]

array([7, 9])

In [37]:
# using logical operator it return true and false
num3>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

# 3. Basic array operations

In [38]:
arr1=np.arange(0,5)
arr2=np.arange(6,11)

In [39]:
arr1+arr2

array([ 6,  8, 10, 12, 14])

In [40]:
arr2-arr1

array([6, 6, 6, 6, 6])

In [41]:
arr1*arr2

array([ 0,  7, 16, 27, 40])

In [42]:
arr1/arr2

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [43]:
# square of complete array
arr1**2

array([ 0,  1,  4,  9, 16])

In [44]:
# doing 5 power of array
arr1**5

array([   0,    1,   32,  243, 1024], dtype=int32)

## 3.2 universal functions

In [45]:
# numpy ufunc allows us to compute math,trigonomatric,logical and all operations.
np.add(arr1,arr2)

array([ 6,  8, 10, 12, 14])

In [46]:
np.multiply(arr1,arr2)
# for multiplication

array([ 0,  7, 16, 27, 40])

In [47]:
np.subtract(arr1,arr2)

array([-6, -6, -6, -6, -6])

In [48]:
np.divide(arr1,arr2)

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [49]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [50]:
np.log(arr2)

array([1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [51]:
# for explonantial
np.exp(arr2)

array([  403.42879349,  1096.63315843,  2980.95798704,  8103.08392758,
       22026.46579481])

In [52]:
# comparison operator return true and false
np.greater(arr1,arr2)

array([False, False, False, False, False])

In [53]:
np.less(arr1,arr2)

array([ True,  True,  True,  True,  True])

#  4. basic statistics

In [54]:
arr=np.arange(0,5)

In [55]:
# standard deviation
np.std(arr)

1.4142135623730951

In [56]:
# variance
np.var(arr)

2.0

In [57]:
# mean
np.mean(arr)

2.0

In [58]:
#mean and average are same
np.average(arr)

2.0

In [59]:
# median
np.median(arr)

2.0

In [60]:
# calculating minimum value in array
np.min(arr)

0

In [61]:
# calculating max. value in array
np.max(arr)

4

#  5. data manipulation

In [62]:
# shape of the array
arr1=np.arange(0,10)
arr2=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [63]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
# shape of array
np.shape(arr1)

(10,)

In [66]:
np.shape(arr2)

(3, 3)

In [67]:
# reshaping the array
np.reshape(arr1,newshape=(5,2))
# it means we convert array into a 2d array which has 5 rows and 2 column

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [68]:
# this also work
arr1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [69]:
arr2_new=arr2.reshape(9,1)

In [70]:
arr2_new

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [71]:
arr2_new.T
# it do the transpose

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [72]:
# copying array
arr1_copy=arr1.copy()

In [73]:
arr1_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
# copying 1 array into another
# for that both array must be of same dimensional
numb1=np.arange(0,6)
numb2=np.arange(6,12)

In [75]:
np.copyto(numb1,numb2)

In [76]:
numb1
# data of previous array is deleted and new data is copied

array([ 6,  7,  8,  9, 10, 11])

In [77]:
numb2

array([ 6,  7,  8,  9, 10, 11])

In [78]:
# joining arrays
arr1=np.array([(1,2,3),(4,5,6),(7,8,9)])
arr2=np.array([(5,6,7)])

In [79]:
#concatente
np.concatenate((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [5, 6, 7]])

In [80]:
np.concatenate((arr1, arr2.T),axis=1)
# we have to use axis

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 7]])

In [81]:
np.concatenate((arr1,arr2),axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 6, 7])

In [82]:
# stacking : joining 2 1d array into 2d array
arr1=np.arange(0,6)
arr2=np.arange(6,12)

In [83]:
# column stacking
np.column_stack((arr1,arr2))

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [84]:
# row stacking
np.row_stack((arr1,arr2))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [85]:
# splitting array
np.split(arr1,3)

[array([0, 1]), array([2, 3]), array([4, 5])]

In [86]:
# adding a element into array
np.append(arr1,7)

array([0, 1, 2, 3, 4, 5, 7])

In [87]:
# we can repeat the array itself multiple times
np.tile(arr1,3)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [88]:
# we can repeat each element of array
np.repeat(arr1,3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [89]:
# sorting
arr=np.array([1,3,0,6,8,4,3,1])

In [90]:
np.sort(arr)

array([0, 1, 1, 3, 3, 4, 6, 8])

In [91]:
# finding unique elements
np.unique(arr)

array([0, 1, 3, 4, 6, 8])

In [92]:
# reverse an array
nump=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [93]:
# up/down flipping
np.flipud(nump)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [94]:
# left/right flip
np.fliplr(nump)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])